# Generated by Django 3.2 on 2021-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
