# Generated by Django 3.2 on 2021-08-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='author',
        ),
    ]
