# Generated by Django 3.2 on 2021-08-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210826_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttt',
            name='target',
        ),
    ]
