# Generated by Django 3.2 on 2021-10-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_commenttt_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttt',
            name='commenttt',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.comment'),
            preserve_default=False,
        ),
    ]
