# Generated by Django 3.2 on 2021-10-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_commenttt_commenttt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttt',
            name='commenttt',
        ),
    ]
